# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2025'
email: eric.s.torstenson@vumc.org
full_name: Eric S Torstenson
gh_action_docs_preview: false
gh_action_pypi: false
github_org: include-dcc
license: MIT
project_description: TBD
project_name: INCLUDE LinkML Data Model
project_slug: include_linkml_data_model

